mysite/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('transactions.urls')),
]

transactions/urls.py
from django.conf.urls import url

from . import views

app_name = 'transactions'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^run/$', views.run, name='run'),
]

transactions/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=32)
    score = models.IntegerField()

transactions/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpRequest, HttpResponseRedirect
from django_ajax.decorators import ajax

from multiprocessing import Process

from .models import User
from django.db import connection

from pprint import pprint

def index(request: HttpRequest):
    return render(request, 'transactions/index.html', {'users': User.objects.all()})

class ResultsView(generic.TemplateView):
    template_name = 'transactions/results.html'

def run_transaction(isolation_level: str, query: str):
    set_level = "SET TRANSACTION ISOLATION LEVEL " + isolation_level + ";"
    with connection.cursor() as cursor:
        cursor.execute(set_level + query)

@ajax
def run(request: HttpRequest):
    isolation_level = request.POST.get("isolation_level")
    q1 = request.POST.get("sql1")
    q2 = request.POST.get("sql2")

    p1 = Process(target=run_transaction, args=(isolation_level, q1,))
    p2 = Process(target=run_transaction, args=(isolation_level, q2,))

    p1.start()
    p2.start()

    p1.join()
    p2.join()

    return render(request, 'transactions/table.html', {'users': User.objects.all()})

transactions/templates/transactions/index.html
{% load static %}
{% load render_table from django_tables2 %}

<h1>Execute concurrent transactions</h1>

<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
<script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>

<script type="text/javascript">
     function rewriteTable(content) {
         $( "#resultTable" ).html( content );
     }
 </script>

<form action="{% url 'transactions:run' %}" method="post" data-ajax-submit="true" data-success="rewriteTable">
{% csrf_token %}
<input type="submit" value="Run" /><br />
<label>Isolation level: </label><br />
<select name="isolation_level">
  <option value="READ UNCOMMITTED">READ UNCOMMITTED</option>
  <option value="READ COMMITTED">READ COMMITTED</option>
  <option selected value="REPEATABLE READ">REPEATABLE READ</option>
  <option value="SERIALIZABLE">SERIALIZABLE</option>
</select><br/>
<div style="display: inline-block;">
	<div id="result" style="float:left;">
	<label>Data: </label><br />
	<div id="resultTable">{% render_table users %}</div>
	</div>
	<div id="first" style="float:left;">
	<label>Input 1st transaction:</label><br />
	<textarea name="sql1" cols="40" rows="50">
SELECT SLEEP(2);
DELETE FROM transactions_user WHERE name="petya";
INSERT INTO transactions_user (name, score) VALUES ("petya2", 2)
	</textarea>
	</div>
	<div id="second" style="float:right;">
	<label>Input 2nd transaction:</label><br />
	<textarea name="sql2" cols="40" rows="50">
INSERT INTO transactions_user (name, score) VALUES ("petya", 2)
	</textarea>
	</div>
</div>
</form>

transactions/templates/transactions/table.html
{% load render_table from django_tables2 %}

{% render_table users %}